# This workflow builds and publishes package distribution to PyPI

name: Publish

# controls when the action will run
on:
  push:
    branches:
      - 'master'

jobs:
  publish_testpypi:
    runs-on: ubuntu-latest
    environment: testpypi
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install poetry 1.1.7
        uses: snok/install-poetry@v1
        with:
          version: 1.1.7

      - name: install dependencies
        run: poetry install

      - name: test
        run: |
          source $(poetry env info --path)/bin/activate # activate virtual environment
          mypy tests

      - name: build
        run: poetry build

      - name: publish testpypi
        env:
          POETRY_REPOSITORIES_TESTPYPI_URL: https://test.pypi.org/legacy/
          POETRY_HTTP_BASIC_TESTPYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: ${{secrets.TESTPYPI_API_TOKEN}}
        run: poetry publish -r testpypi

  publish_pypi:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install poetry 1.1.7
        uses: snok/install-poetry@v1
        with:
          version: 1.1.7

      - name: install dependencies
        run: poetry install

      - name: test
        run: mypy tests

      - name: build
        run: poetry build

      - name: publish pypi
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{secrets.PYPI_API_TOKEN}}
        run: poetry publish
