# This workflow tests our package

name: Test

# Controls when the action will run
on:
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # Create and activate virtualenv
          python3 -m venv .venv && source .venv/bin/activate
          # Make sure to have the latest pip version installed
          python -m pip install --upgrade pip
          pip install mypy

      - name: Test
        run: |
          source .venv/bin/activate
          # test to install our package in “editable” mode
          pip install -e .
          # Run tests
          mypy tests
